# -*- coding: utf-8 -*-
"""Vectorial_RGB_visuals_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JIeNg9IPBVne0lZezj84vCN6UxPWzvm0
"""

import cv2
import numpy as np
import torch

# Install LPIPS automatically when running in Google Colab
try:
    import lpips
except ImportError:
    import sys
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "lpips"])
    import lpips

from skimage.metrics import structural_similarity as ssim
from skimage.metrics import peak_signal_noise_ratio as psnr
from skimage.restoration import denoise_nl_means
from skimage.restoration import estimate_sigma

from scipy.ndimage import convolve
from pathlib import Path



# Helper Functions

def gradient_vectorial(u):

    grad_u = np.zeros(u.shape + (2,), dtype=np.float32)

    grad_u[:-1, :, :, 0] = u[1:, :, :] - u[:-1, :, :]
    grad_u[:, :-1, :, 1] = u[:, 1:, :] - u[:, :-1, :]

    return grad_u


def divergence_vectorial(p):

    div = np.zeros(p.shape[:3], dtype=np.float32)

    div[:-1, :, :] += p[:-1, :, :, 0]
    div[1:, :, :] -= p[:-1, :, :, 0]

    div[:, :-1, :] += p[:, :-1, :, 1]
    div[:, 1:, :] -= p[:, :-1, :, 1]

    return div


def frobenius_norm(p):

    return np.sqrt(np.sum(p**2, axis=(2, 3)) + 1e-12)


def chambolle_pock_vectorial_rof(image, tau, lam=0.2, max_iter=10000, tol=1e-5):

    m, n, channels = image.shape

    p = np.zeros((m, n, channels, 2), dtype=np.float32)

    x = image.copy()
    x_bar = x.copy()

    L = np.sqrt(8.0)
    sigma_cp = 1.0 / (tau * L * L)

    for i in range(max_iter):

        g = gradient_vectorial(x_bar)

        p_new = p + sigma_cp * g

        norm_p = frobenius_norm(p_new)

        p = p_new / np.maximum(1.0, norm_p / lam)[..., None, None]

        div_p = divergence_vectorial(p)

        x_prev = x.copy()

        x = (x + tau * (div_p + image)) / (1.0 + tau)

        theta = 1.0 / np.sqrt(1.0 + tau / 2.0)

        tau *= theta
        sigma_cp /= theta

        x_bar = x + theta * (x - x_prev)

        if np.linalg.norm(x - x_prev) < tol:
            break

    return x

def norm2(p):

    return np.sqrt(np.sum(p**2, axis=-1) + 1e-12)

def gradient(u):

    grad_u = np.zeros(u.shape + (2,), dtype=np.float32)

    grad_u[:-1, :, 0] = (u[1:, :] - u[:-1, :])

    grad_u[:, :-1, 1] = (u[:, 1:] - u[:, :-1])

    return grad_u


def divergence(p):

    div = np.zeros(p.shape[:2], dtype=np.float32)

    div[:-1, :] += p[:-1, :, 0]
    div[1:, :] -= p[:-1, :, 0]

    div[:, :-1] += p[:, :-1, 1]
    div[:, 1:] -= p[:, :-1, 1]

    return div

def chambolle_pock_v(image, tau, lam=np.float32(0.2), max_iter=10000, tol=np.float32(1e-5)):

    m, n = image.shape

    p = np.zeros((m, n, 2), dtype=np.float32)

    x = image.copy()
    x_bar = x.copy()

    L = np.float32(np.sqrt(np.float32(8.0)))
    sigma_cp = np.float32(1.0 / (tau * L * L))
    theta = np.float32(1.0)

    for i in range(max_iter):

        g = gradient(x_bar)

        p_new = p + sigma_cp * g

        norm_p = norm2(p_new)
        p = p_new / np.maximum(np.float32(1.0), norm_p[..., None] / lam)

        div_p = divergence(p)

        x_prev = x.copy()

        x = (x + tau * (div_p + image)) / (np.float32(1.0) + tau)

        theta = np.float32(1.0 / np.sqrt(np.float32(1.0) + tau / np.float32(2.0)))

        tau *= theta
        sigma_cp /= theta

        x_bar = x + theta * (x - x_prev)

        if np.linalg.norm(x - x_prev) < tol:
            break

    return x

def ball_kernel(radius):

    y, x = np.ogrid[-radius:radius + 1, -radius:radius + 1]
    mask = x**2 + y**2 <= radius**2
    kernel = mask.astype(np.float32)
    kernel /= np.sum(kernel)

    return kernel


def mollify_function(func, radius=2):

    kernel = ball_kernel(radius)
    padded = np.pad(func, pad_width=radius, mode="reflect")
    mollified = convolve(padded, kernel, mode="reflect")
    return mollified[radius:-radius,radius:-radius]

def mollify_rgb(image, radius=2):

    kernel = ball_kernel(radius)
    mollified = np.zeros_like(image, dtype=np.float32)

    for channel in range(image.shape[2]):

        padded = np.pad(
            image[:, :, channel],
            pad_width=radius,
            mode="reflect"
        )

        mollified_channel = convolve(
            padded,
            kernel,
            mode="reflect"
        )

        mollified[:, :, channel] = mollified_channel[
            radius:-radius,
            radius:-radius
        ]

    return mollified


def custom_resolvent_vectorial(p_tilde, a, sigma, lam):

    norm_p = frobenius_norm(p_tilde)

    p = np.zeros_like(p_tilde)

    mask_zero = a == 0
    mask_small = (a > 0) & (norm_p <= lam)
    mask_large = (a > 0) & (norm_p > lam)

    p[mask_zero] = (
        p_tilde[mask_zero] /
        np.maximum(1.0, norm_p[mask_zero] / lam)[..., None, None]
    )

    p[mask_small] = p_tilde[mask_small]

    s = norm_p[mask_large]
    a_values = a[mask_large]

    factor = (
        (sigma / s + a_values) /
        (sigma / lam + a_values)
    )

    p[mask_large] = p_tilde[mask_large] * factor[..., None, None]

    return p


def chambolle_pock_vectorial_dprof(image, a_weight, tau, lam=0.2, max_iter=10000, tol=1e-5):

    m, n, channels = image.shape

    p = np.zeros((m, n, channels, 2), dtype=np.float32)

    x = image.copy()
    x_bar = x.copy()

    L = np.sqrt(8.0)
    sigma_cp = 1.0 / (tau * L * L)

    for i in range(max_iter):

        g = gradient_vectorial(x_bar)

        p_new = p + sigma_cp * g

        p = custom_resolvent_vectorial(
            p_new,
            a_weight,
            sigma_cp,
            lam
        )

        div_p = divergence_vectorial(p)

        x_prev = x.copy()

        x = (x + tau * (div_p + image)) / (1.0 + tau)

        theta = 1.0 / np.sqrt(1.0 + tau / 2.0)

        tau *= theta
        sigma_cp /= theta

        x_bar = x + theta * (x - x_prev)

        if np.linalg.norm(x - x_prev) < tol:
            break

    return x

def custom_resolvent_v(p_tilde, a, sigma, lam):

    norm_p = norm2(p_tilde)

    p = np.zeros_like(p_tilde)

    mask_zero = a == 0
    mask_small = (a > 0) & (norm_p <= lam)
    mask_large = (a > 0) & (norm_p > lam)

    p[mask_zero] = p_tilde[mask_zero] / np.maximum(1.0, norm_p[mask_zero][..., None] / lam)
    p[mask_small] = p_tilde[mask_small]

    s = norm_p[mask_large]
    a_values = a[mask_large]

    factor = (sigma / s + a_values) / (sigma / lam + a_values)

    p[mask_large] = p_tilde[mask_large] * factor[..., None]

    return p


def chambolle_pock_modified_v(image, a_weight, tau, lam=0.2, max_iter=10000, tol=1e-5):

    m, n = image.shape

    p = np.zeros((m, n, 2), dtype=np.float32)

    x = image.copy()
    x_bar = x.copy()

    L = np.sqrt(8.0)
    sigma_cp = 1.0 / (tau * L * L)
    theta = 1.0

    for i in range(max_iter):

        g = gradient(x_bar)

        p_new = p + sigma_cp * g

        p = custom_resolvent_v(p_new, a_weight, sigma_cp, lam)

        div_p = divergence(p)

        x_prev = x.copy()

        x = (x + tau * (div_p + image)) / (1.0 + tau)

        theta = 1.0 / np.sqrt(1.0 + tau / 2.0)

        tau *= theta
        sigma_cp /= theta

        x_bar = x + theta * (x - x_prev)

        if np.linalg.norm(x - x_prev) < tol:
            break

    return x

##############################################################################
# Utility Functions
##############################################################################

def normalize_to_uint8(x):

    x = x - x.min()
    x = x / (x.max() + 1e-12)

    return (255.0 * x).astype(np.uint8)


def float_to_uint8(x):

    return np.clip(255.0 * x, 0.0, 255.0).astype(np.uint8)


def show_image(title, image, width=963, height=1443):

    cv2.namedWindow(title, cv2.WINDOW_NORMAL)
    cv2.resizeWindow(title, width, height)
    cv2.imshow(title, image)


def conversion_for_lpips(image, device):

    image_lpips = np.transpose(image, (2, 0, 1))
    image_lpips = torch.from_numpy(image_lpips.copy()).float()
    image_lpips = image_lpips.unsqueeze(0)
    image_lpips = image_lpips * 2.0 - 1.0

    return image_lpips.to(device)


##############################################################################
################ Parameters according to noise levels  #######################
##############################################################################

noise_sigma = 0.2
noise_variance = noise_sigma**2
random_seed = 0

if noise_variance <= 0.005:

    noise_level = "small"
    lambda_ROF = 1.0 * noise_sigma
    lambda_dpROF = 0.8 * noise_sigma
    a_dpROF = 20.0
    b_over_a = 50.0

elif noise_variance <= 0.015:

    noise_level = "medium"
    lambda_ROF = 1.1 * noise_sigma
    lambda_dpROF = 0.9 * noise_sigma
    a_dpROF = 100.0
    b_over_a = 50.0

else:

    noise_level = "large"
    lambda_ROF = 1.2 * noise_sigma
    lambda_dpROF = 0.9 * noise_sigma
    a_dpROF = 100.0
    b_over_a = 50.0

b_dpROF = a_dpROF * b_over_a

given_precision_ROF = 1e-4
given_precision_dpROF = 1e-4

tau_initial = 0.25
max_iter_ROF = 20000
max_iter_dpROF = 20000
mollifier_radius = 2

h_factor = 0.45

print(f"Noise level: {noise_level}")
print(f"Noise standard deviation: {noise_sigma}")
print(f"Noise variance: {noise_variance}")
print(f"lambda_ROF: {lambda_ROF}")
print(f"lambda_dpROF: {lambda_dpROF}")
print(f"a: {a_dpROF}")
print(f"b/a: {b_over_a}")
print(f"b: {b_dpROF}")
print(f"h_factor: {h_factor}")

##############################################################################
############################## Input Image   #################################
##############################################################################

# Google Colab: upload the input image from your computer
try:
    from google.colab import files
    uploaded = files.upload()

    if len(uploaded) == 0:
        raise ValueError("No image was uploaded.")

    uploaded_name = next(iter(uploaded))
    path = Path(uploaded_name)

except ImportError:
    # Fallback if the script is executed outside Google Colab
    path = Path("lady.jpg")

output_dir = Path("/content/results") if Path("/content").exists() else path.parent
output_dir.mkdir(parents=True, exist_ok=True)

img = cv2.imread(str(path), cv2.IMREAD_COLOR)

if img is None:
    raise ValueError(f"Image not found or could not be read: {path}")

#img = cv2.resize(img, (648, 486), interpolation=cv2.INTER_AREA)

clean_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0

rng = np.random.default_rng(random_seed)

gaussian_noise = rng.normal(loc=0.0,scale=noise_sigma,size=clean_rgb.shape).astype(np.float32)

noisy_rgb = np.clip(clean_rgb + gaussian_noise,0.0,1.0).astype(np.float32)

#####################################################
########## Denoising models implementation ##########
#####################################################

print("Running initial vectorial RGB ROF")
denoised_rgb_rof = chambolle_pock_vectorial_rof(noisy_rgb,tau=tau_initial,lam=lambda_ROF,max_iter=max_iter_ROF,tol=given_precision_ROF)

print("Constructing adaptive weight")
mollified_rgb_rof = mollify_rgb(denoised_rgb_rof,radius=mollifier_radius)
grad_rgb_rof = gradient_vectorial(mollified_rgb_rof)
grad_frobenius = frobenius_norm(grad_rgb_rof)

a_weight = np.maximum(0.0,a_dpROF -b_dpROF * np.maximum(grad_frobenius,a_dpROF / (2.0 * b_dpROF))).astype(np.float32)


print("Frobenius gradient min:", grad_frobenius.min())
print("Frobenius gradient max:", grad_frobenius.max())
print("Frobenius gradient mean:", grad_frobenius.mean())
print("Frobenius gradient median:", np.median(grad_frobenius))


print(f"Weight min: {a_weight.min()}")
print(f"Weight max: {a_weight.max()}")
print(f"Weight mean: {a_weight.mean()}")
print(f"Weight median: {np.median(a_weight)}")

print("Running vectorial RGB dpROF")
denoised_rgb_dprof = chambolle_pock_vectorial_dprof(noisy_rgb,a_weight,tau=tau_initial,lam=lambda_dpROF,max_iter=max_iter_dpROF,tol=given_precision_dpROF)

# Clip Results to [0,1]

denoised_rgb_rof_clipped = np.clip(denoised_rgb_rof,0.0,1.0)
denoised_rgb_dprof_clipped = np.clip(denoised_rgb_dprof,0.0,1.0)

noise_sigma_est = np.mean(estimate_sigma(noisy_rgb, channel_axis=-1))

print(f"Estimated sigma for NL means: {noise_sigma_est}")

denoised_nl = denoise_nl_means(noisy_rgb, h = h_factor * noise_sigma_est,
                sigma = noise_sigma_est, # estimated noise std
                fast_mode = True,
                channel_axis = -1
            )

clean_yuv = cv2.cvtColor(clean_rgb, cv2.COLOR_RGB2YUV)

noisy_yuv = cv2.cvtColor(noisy_rgb, cv2.COLOR_RGB2YUV)

clean_Y, clean_U, clean_V = cv2.split(clean_yuv)
clean_R, clean_G, clean_B = cv2.split(clean_rgb)

noisy_Y, noisy_U, noisy_V = cv2.split(noisy_yuv)
noisy_R, noisy_G, noisy_B = cv2.split(noisy_rgb)

clean_Y = clean_Y.astype(np.float32)
clean_U = clean_U.astype(np.float32)
clean_V = clean_V.astype(np.float32)

clean_R = clean_R.astype(np.float32)
clean_G = clean_G.astype(np.float32)
clean_B = clean_B.astype(np.float32)

noisy_Y = noisy_Y.astype(np.float32)
noisy_U = noisy_U.astype(np.float32)
noisy_V = noisy_V.astype(np.float32)

noisy_R = noisy_R.astype(np.float32)
noisy_G = noisy_G.astype(np.float32)
noisy_B = noisy_B.astype(np.float32)


#####################################################
########## Denoising models implementation ##########
#####################################################

# Parameter selection according to the noise variance.

if noise_variance <= 0.005:

    noise_level = "small"

    lambda_ROF_v = np.float32(0.7) * noise_sigma
    lambda_dpROF_v = np.float32(0.5) * noise_sigma

    a_dpROF_v = np.float32(60.0)
    b_over_a_v = np.float32(100.0)

elif noise_variance <= 0.015:

    noise_level = "medium"

    lambda_ROF_v = np.float32(0.7) * noise_sigma
    lambda_dpROF_v = np.float32(0.5) * noise_sigma

    a_dpROF_v = np.float32(60.0)
    b_over_a_v = np.float32(50.0)

else:

    noise_level = "large"

    lambda_ROF_v = np.float32(0.8) * noise_sigma
    lambda_dpROF_v = np.float32(0.5) * noise_sigma

    a_dpROF_v = np.float32(60.0)
    b_over_a_v = np.float32(25.0)

# Classical ROF on Y, U and V



print("Running classical ROF on Y...")
denoised_Y_rof = chambolle_pock_v(noisy_Y, tau=0.25, lam=lambda_ROF_v, max_iter=20000, tol=given_precision_ROF)

print("Running classical ROF on U...")
denoised_U_rof = chambolle_pock_v(noisy_U, tau=0.25, lam=lambda_ROF_v, max_iter=20000, tol=given_precision_ROF)

print("Running classical ROF on V...")
denoised_V_rof = chambolle_pock_v(noisy_V, tau=0.25, lam=lambda_ROF_v, max_iter=20000, tol=given_precision_ROF)

print("Running classical ROF on R...")
denoised_R_rof = chambolle_pock_v(noisy_R, tau=0.25, lam=lambda_ROF_v, max_iter=20000, tol=given_precision_ROF)

print("Running classical ROF on G...")
denoised_G_rof = chambolle_pock_v(noisy_G, tau=0.25, lam=lambda_ROF_v, max_iter=20000, tol=given_precision_ROF)

print("Running classical ROF on B...")
denoised_B_rof = chambolle_pock_v(noisy_B, tau=0.25, lam=lambda_ROF_v, max_iter=20000, tol=given_precision_ROF)


# Initial ROF used to construct the dpROF Weight

print("Running initial ROF for dpROF weight...")

denoised_Y_initial = denoised_Y_rof

denoised_R_initial = denoised_R_rof
denoised_G_initial = denoised_G_rof
denoised_B_initial = denoised_B_rof

#chambolle_pock_v(noisy_Y, tau=0.25, lam=lambda_ROF_v, max_iter=20000, tol=given_precision_dpROF)
mollified_Y_initial = mollify_function(denoised_Y_initial, radius=2)

mollified_R_initial = mollify_function(denoised_R_initial, radius=2)
mollified_G_initial = mollify_function(denoised_G_initial, radius=2)
mollified_B_initial = mollify_function(denoised_B_initial, radius=2)

grad_Y_initial = gradient(mollified_Y_initial)

grad_R_initial = gradient(mollified_R_initial)
grad_G_initial = gradient(mollified_G_initial)
grad_B_initial = gradient(mollified_B_initial)

grad_norm_Y = norm2(grad_Y_initial)

grad_norm_R = norm2(grad_R_initial)
grad_norm_G = norm2(grad_G_initial)
grad_norm_B = norm2(grad_B_initial)

a_const = a_dpROF_v
b_const = b_over_a_v * a_dpROF_v

a_weight_v = np.maximum(0, a_const - b_const * np.maximum(grad_norm_Y, a_const / (2 * b_const))).astype(np.float32)

a_weight_v_R = np.maximum(0, a_const - b_const * np.maximum(grad_norm_R, a_const / (2 * b_const))).astype(np.float32)
a_weight_v_G = np.maximum(0, a_const - b_const * np.maximum(grad_norm_G, a_const / (2 * b_const))).astype(np.float32)
a_weight_v_B = np.maximum(0, a_const - b_const * np.maximum(grad_norm_B, a_const / (2 * b_const))).astype(np.float32)

# dpROF on Y, U and V

# The structural information and the weight function are computed only from the Y channel.
# The same Y-derived weight is used for the separate denoising of Y, U and V.

print("Running dpROF on Y...")
denoised_Y_dprof = chambolle_pock_modified_v(noisy_Y, a_weight_v, tau=0.25, lam=lambda_dpROF_v, max_iter=20000, tol=given_precision_dpROF)

print("Running dpROF on U...")
denoised_U_dprof = chambolle_pock_modified_v(noisy_U, a_weight_v, tau=0.25, lam=lambda_dpROF_v, max_iter=20000, tol=given_precision_dpROF)

print("Running dpROF on V...")
denoised_V_dprof = chambolle_pock_modified_v(noisy_V, a_weight_v, tau=0.25, lam=lambda_dpROF_v, max_iter=20000, tol=given_precision_dpROF)

print("Running dpROF on R...")
denoised_R_dprof = chambolle_pock_modified_v(noisy_R, a_weight_v_R, tau=0.25, lam=lambda_dpROF_v, max_iter=20000, tol=given_precision_dpROF)

print("Running dpROF on G...")
denoised_G_dprof = chambolle_pock_modified_v(noisy_G, a_weight_v_G, tau=0.25, lam=lambda_dpROF_v, max_iter=20000, tol=given_precision_dpROF)

print("Running dpROF on B...")
denoised_B_dprof = chambolle_pock_modified_v(noisy_B, a_weight_v_B, tau=0.25, lam=lambda_dpROF_v, max_iter=20000, tol=given_precision_dpROF)

# Clip the Denoised YUV Channels to [0,1]
# The optimization itself is unconstrained. Small values outside [0,1] may therefore occur.
# Clipping is applied only before reconstruction and visualization.

denoised_Y_rof_clipped = np.clip(denoised_Y_rof, 0.0, 1.0).astype(np.float32)
denoised_U_rof_clipped = np.clip(denoised_U_rof, 0.0, 1.0).astype(np.float32)
denoised_V_rof_clipped = np.clip(denoised_V_rof, 0.0, 1.0).astype(np.float32)

denoised_R_rof_clipped = np.clip(denoised_R_rof, 0.0, 1.0).astype(np.float32)
denoised_G_rof_clipped = np.clip(denoised_G_rof, 0.0, 1.0).astype(np.float32)
denoised_B_rof_clipped = np.clip(denoised_B_rof, 0.0, 1.0).astype(np.float32)

denoised_Y_dprof_clipped = np.clip(denoised_Y_dprof, 0.0, 1.0).astype(np.float32)
denoised_U_dprof_clipped = np.clip(denoised_U_dprof, 0.0, 1.0).astype(np.float32)
denoised_V_dprof_clipped = np.clip(denoised_V_dprof, 0.0, 1.0).astype(np.float32)

denoised_R_dprof_clipped = np.clip(denoised_R_dprof, 0.0, 1.0).astype(np.float32)
denoised_G_dprof_clipped = np.clip(denoised_G_dprof, 0.0, 1.0).astype(np.float32)
denoised_B_dprof_clipped = np.clip(denoised_B_dprof, 0.0, 1.0).astype(np.float32)


##############################################################################
#############    Reconstruct Color Images  ###################################
##############################################################################

# Classical ROF result: Y, U and V are denoised independently.

yuv_rof = cv2.merge((denoised_Y_rof_clipped, denoised_U_rof_clipped, denoised_V_rof_clipped)).astype(np.float32)
yuv_rof = cv2.cvtColor(yuv_rof, cv2.COLOR_YUV2RGB)
yuv_rof = np.clip(yuv_rof, 0.0, 1.0)

rgb_rof = cv2.merge((denoised_R_rof_clipped, denoised_G_rof_clipped, denoised_B_rof_clipped)).astype(np.float32)
rgb_rof = np.clip(rgb_rof, 0.0, 1.0)

# dpROF result: Y, U and V are denoised independently.
# The same weight computed from Y is used for all three channels.

yuv_dprof = cv2.merge((denoised_Y_dprof_clipped, denoised_U_dprof_clipped, denoised_V_dprof_clipped)).astype(np.float32)
yuv_dprof = cv2.cvtColor(yuv_dprof, cv2.COLOR_YUV2RGB)
yuv_dprof = np.clip(yuv_dprof, 0.0, 1.0)

rgb_dprof = cv2.merge((denoised_R_dprof_clipped, denoised_G_dprof_clipped, denoised_B_dprof_clipped)).astype(np.float32)
rgb_dprof = np.clip(rgb_dprof, 0.0, 1.0)


##############################################################################
############################ Visualization ###################################
##############################################################################

import matplotlib.pyplot as plt



# Clean / Noisy / ROF / dpROF / Adaptive weight

images = [
    clean_rgb,
    denoised_rgb_rof_clipped,
    rgb_rof,
    denoised_nl,
    noisy_rgb,
    denoised_rgb_dprof_clipped,
    rgb_dprof,
    yuv_dprof
]

titles = [
    "Original",
    "Vec-ROF",
    "RGB-ROF",
    "NL-means",
    "Noisy",
    "Vec-dpROF",
    "RGB-dpROF",
    "YUV-dpROF"
]

fig, axes = plt.subplots(2, 4, figsize=(12, 9), constrained_layout=True)

for ax, img_vis, title in zip(axes.flatten(), images, titles):
    ax.imshow(np.clip(img_vis, 0.0, 1.0))
    ax.set_title(title, fontsize = 10 )
    ax.axis("off")

#plt.tight_layout(pad=2)

plt.savefig(
    str(output_dir / "denoised_images_rgb.png"),
    dpi=300,
    bbox_inches="tight"
)

plt.show()
plt.close()



# Adaptive weight

images = [
    a_weight,
    a_weight_v_R,
    a_weight_v_G,
    a_weight_v_B,
    a_weight_v
]

titles = [
    "Vec dpROF weight",
    "R dpROF weight",
    "G dpROF weight",
    "B dpROF weight",
    "Y dpROF weight"
]

fig, axes = plt.subplots(1, 5, figsize =(10, 4), constrained_layout=True)


for ax, img, title in zip(axes.flatten(), images, titles):
    im = ax.imshow(img, cmap="jet")
    ax.set_title(title, fontsize = 8)
    ax.axis("off")
    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

plt.savefig(
    str(output_dir / "adaptive_weights.png"),
    dpi=300,
    bbox_inches="tight"
)

plt.show()
plt.close()



# Absolute error maps
# For RGB images, compute one scalar error value per pixel by averaging the absolute error over the three channels.

error_rof = np.mean(
    np.abs(denoised_rgb_rof_clipped - clean_rgb),
    axis=2
)

error_rgbrof = np.mean(
    np.abs(rgb_rof - clean_rgb),
    axis=2
)

error_nlm = np.mean(
    np.abs(denoised_nl - clean_rgb),
    axis=2
)

error_dprof = np.mean(
    np.abs(denoised_rgb_dprof_clipped - clean_rgb),
    axis=2
)

error_rgbdprof = np.mean(
    np.abs(rgb_dprof - clean_rgb),
    axis=2
)

error_yuvdprof = np.mean(
    np.abs(yuv_dprof - clean_rgb),
    axis=2
)



error_maps = [
    error_rof,
    error_rgbrof,
    error_nlm,
    error_dprof,
    error_rgbdprof,
    error_yuvdprof
]

error_titles = [
    "Error map: Vec ROF",
    "Error map: RGB ROF",
    "Error map: NL means",
    "Error map: Vec dpROF",
    "Error map: RGB dpROF",
    "Error map: YUV dpROF"
]

fig, axes = plt.subplots(1, 6, figsize=(10, 3), constrained_layout=True)

# Same scale for all methods
vmax_error = max(np.percentile(error_rof, 99),np.percentile(error_dprof, 99), np.percentile(error_yuvdprof, 99),
                 np.percentile(error_rgbdprof, 99), np.percentile(error_rgbrof, 99), np.percentile(error_nlm, 99))

for ax, error_map, title in zip(axes.flatten(), error_maps, error_titles):

    im = ax.imshow(
        error_map,
        cmap="hot",
        vmin=0.0,
        vmax=vmax_error
    )

    ax.set_title(title, fontsize=8)
    ax.axis("off")

plt.colorbar(
        im,
        ax=ax,
        fraction=0.046,
        pad=0.04)

plt.savefig(
    str(output_dir / "difference_to_clean_rgb.png"),
    dpi=300,
    bbox_inches="tight"
)

plt.show()
plt.close()


# Difference between dpROF and ROF error
#
# Negative values: dpROF has smaller error than ROF
# Positive values: dpROF has larger error than ROF

error_diff_rof = error_dprof - error_rof
error_diff_rgbrof = error_dprof - error_rgbrof
error_diff_nlm = error_dprof - error_nlm
error_diff_yuv = error_dprof - error_yuvdprof
error_diff_rgb = error_dprof - error_rgbdprof
error_diffs = [error_diff_rof, error_diff_rgbrof, error_diff_nlm, error_diff_yuv, error_diff_rgb]

fig, axes = plt.subplots(1, 5, figsize=(10, 4), constrained_layout=True)

error_diff_titles = [
    "Error diff: Vec dpROF−Vec ROF",
    "Error diff: Vec dpROF−RGB ROF",
    "Error diff: Vec dpROF−NLM",
    "Error diff: Vec dpROF−RGB dpROF",
    "Error diff: Vec dpROF−YUV dpROF"
]

# Symmetric scale around zero
max_abs_diff = max(np.percentile(np.abs(error_diff_rof), 99), np.percentile(np.abs(error_diff_yuv), 99), np.percentile(np.abs(error_diff_rgbrof), 99),
                   np.percentile(np.abs(error_diff_rgb), 99), np.percentile(np.abs(error_diff_nlm), 99))

for ax, error_diff, title in zip(axes.flatten(), error_diffs, error_diff_titles):

  im = ax.imshow(
      error_diff,
      cmap="seismic",
      vmin=-max_abs_diff,
      vmax=max_abs_diff
  )

  ax.set_title(
      title,
      fontsize=8
  )

  ax.axis("off")

plt.colorbar(
      im,
      ax=ax,
      fraction=0.046,
      pad=0.04)

plt.savefig(
    str(output_dir / "error_diffs_rgb.png"),
    dpi=300,
    bbox_inches="tight"
)

plt.show()
plt.close()

##############################################################################
########################## Computation of Metrics   ##########################
##############################################################################

device = "cuda" if torch.cuda.is_available() else "cpu"

loss_fn = lpips.LPIPS(net="alex").to(device)
loss_fn.eval()

clean_lpips = conversion_for_lpips(clean_rgb, device)
rof_lpips = conversion_for_lpips(denoised_rgb_rof_clipped, device)
rgbrof_lpips = conversion_for_lpips(rgb_rof, device)
dprof_lpips = conversion_for_lpips(denoised_rgb_dprof_clipped, device)
yuvdprof_lpips = conversion_for_lpips(yuv_dprof, device)
rgbdprof_lpips = conversion_for_lpips(rgb_dprof, device)
nlm_lpips = conversion_for_lpips(denoised_nl, device)


# LPIPS

with torch.no_grad():

    lpips_rof = loss_fn(clean_lpips, rof_lpips).item()
    lpips_rgbrof = loss_fn(clean_lpips, rgbrof_lpips).item()
    lpips_dprof = loss_fn(clean_lpips, dprof_lpips).item()
    lpips_nlm = loss_fn(clean_lpips, nlm_lpips).item()
    lpips_yuvdprof = loss_fn(clean_lpips, yuvdprof_lpips).item()
    lpips_rgbdprof = loss_fn(clean_lpips, rgbdprof_lpips).item()


# SSIM


ssim_rof = ssim(clean_rgb,denoised_rgb_rof_clipped,data_range=1.0,channel_axis=-1)
ssim_rgbrof = ssim(clean_rgb, rgb_rof, data_range=1.0,channel_axis=-1)
ssim_dprof = ssim(clean_rgb,denoised_rgb_dprof_clipped,data_range=1.0,channel_axis=-1)
ssim_nlm = ssim(clean_rgb,denoised_nl,data_range=1.0,channel_axis=-1)
ssim_yuvdprof = ssim(clean_rgb,yuv_dprof,data_range=1.0,channel_axis=-1)
ssim_rgbdprof = ssim(clean_rgb,rgb_dprof,data_range=1.0,channel_axis=-1)

# PSNR


psnr_rof = psnr(clean_rgb,denoised_rgb_rof_clipped,data_range=1.0)
psnr_rgbrof = psnr(clean_rgb,rgb_rof,data_range=1.0)
psnr_dprof = psnr(clean_rgb,denoised_rgb_dprof_clipped,data_range=1.0)
psnr_nlm = psnr(clean_rgb,denoised_nl,data_range=1.0)
psnr_yuvdprof = psnr(clean_rgb,yuv_dprof,data_range=1.0)
psnr_rgbdprof = psnr(clean_rgb,rgb_dprof,data_range=1.0)

# Print Metrics

print()
print("Metrics against the clean RGB image")
print()

print(f"Vectorial ROF - LPIPS: {lpips_rof:.6f}")
print(f"RGB ROF - LPIPS: {lpips_rgbrof:.6f}")
print(f"Vectorial dpROF - LPIPS: {lpips_dprof:.6f}")
print(f"YUV dpROF - LPIPS: {lpips_yuvdprof:.6f}")
print(f"RGB dpROF - LPIPS: {lpips_rgbdprof:.6f}")
print(f"NL means - LPIPS: {lpips_nlm:.6f}")

print()

print(f"Vectorial ROF - SSIM: {ssim_rof:.6f}")
print(f"RGB ROF - SSIM: {ssim_rgbrof:.6f}")
print(f"Vectorial dpROF - SSIM: {ssim_dprof:.6f}")
print(f"YUV dpROF - SSIM: {ssim_yuvdprof:.6f}")
print(f"RGB dpROF - SSIM: {ssim_rgbdprof:.6f}")
print(f"NL means - SSIM: {ssim_nlm:.6f}")

print()

print(f"Vectorial ROF - PSNR: {psnr_rof:.4f} dB")
print(f"RGB ROF - PSNR: {psnr_rgbrof:.4f} dB")
print(f"Vectorial dpROF - PSNR: {psnr_dprof:.4f} dB")
print(f"YUV dpROF - PSNR: {psnr_yuvdprof:.4f} dB")
print(f"RGB dpROF - PSNR: {psnr_rgbdprof:.4f} dB")
print(f"NL means - PSNR: {psnr_nlm:.4f} dB")

print()




print("Done.")
